### PR TITLE
Fix unit test races (carry #48)

### PR DESCRIPTION
**Pull request by thaJeztah**
carries: https://github.com/moby/spdystream/pull/48
closes https://github.com/moby/spdystream/pull/48

### CODE REVIEW

**Comment by thaJeztah** [comment]
CI failure is unrelated; will be fixed by https://github.com/moby/spdystream/pull/90

**Comment by thaJeztah** [comment]
@dims PTAL 🤗

**Comment by dims** [comment]
hmm, 90 needs one more approval before we can land that and make this go green here

**Comment by thaJeztah** [comment]
> hmm, 90 needs one more approval before we can land that and make this go green here

I, erm, went slightly ahead and got that one in to fix CI 😅 😇 


@dmcgowan ptal

**Comment by thaJeztah** [comment]
FWIW; I just noticed that https://github.com/moby/spdystream/pull/86 also has a fix for this, so we could choose to take that one as well (I guess either approach would work)

**Review by dmcgowan — APPROVED** [review]

**Comment by dmcgowan** [comment]
Either is fine, #86 is a bit bigger and think it needs some validation

**Comment by aojea** [comment]
/lgtm

I'm going to close #86 since it should no longer needed

**Comment by thaJeztah** [comment]
@dmcgowan I saw you merged another PR; I rebased this one again to get a fresh run of CI 👍

**Review by dmcgowan — APPROVED** [review]

**Pull request merged**
