### PR TITLE
Remove unused websocket package

### PR DESCRIPTION
**Pull request by dmcgowan**
This package serves no purpose and is not imported anywhere https://pkg.go.dev/github.com/moby/spdystream/ws. Remove this to cleanup unnecessary go.sum entries.

### CODE REVIEW

**Review by dims — APPROVED** [review]
LGTM

**Comment by aojea** [comment]
LGTM

**Comment by thaJeztah** [comment]
cc @adisky (if we need another maintainer review, but I'm fine with merging this after the folks above have reviewed it)

**Review by dims — APPROVED** [review]
LGTM

**Pull request merged**
